# Generated by Django 2.2.10 on 2021-03-27 04:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('start_date', models.DateField(editable=False)),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('TXT', 'Text response'), ('CHK', 'Choice of one option'), ('RDO', 'Choice of several options')], default='TXT', max_length=3)),
                ('response_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('required', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.Person')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.Query')),
            ],
        ),
    ]
